import "./globals.css";
import { Roboto_Condensed } from "next/font/google";
const robotocondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotocondensed.className}>{children}</body>
    </html>
  );
}
